config/routes.rb
Cookbook::Application.routes.draw do
resources :books ,:recipes, :ingredients
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  cuisine    :string(255)
#  chef       :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ActiveRecord::Base
	attr_accessible	:title,	:cuisine,:chef, :image
	has_many :recipes
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  cost        :decimal(, )
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ActiveRecord::Base
	attr_accessible	:name, :measurement, :cost, :image
	has_and_belongs_to_many	:recipes
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  course       :string(255)
#  cooktime     :integer
#  servingsize  :integer
#  instructions :integer
#  book_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  image        :text
#

class Recipe < ActiveRecord::Base
	attr_accessible	:name,:course,:cooktime, :servingsize, :instructions, :image, :book_id, recipe_ids
	belongs_to	:book
	has_and_belongs_to_many	:ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
	@books = Book.all
	end

	def show
	@book = Book.find(params[:id]) 
	end

	def create
		book = Book.create(params[:book])
		redirect_to(book)
	end

	def new
		@book = Book.new
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		book = Book.find(params[:id])
		book.update_attributes(params[:book])
		redirect_to(book)
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to(ingredients_path)
	end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	def index
		@ingredients = Ingredient.all
	end

	def show
		@ingredient = Ingredient.find(params[:id])
	end

	def create
		ingredient = Ingredient.create(params[:ingredient])
		redirect_to(ingredient)
	end

	def new
		@ingredient = Ingredient.new
	end

	def edit
		@ingredient = Ingredient.find(params[:id])
	end

	def update
		ingredient = Ingredient.find(params[:id])
		ingredient.update_attributes(params[:ingredient])
		redirect_to(ingredient)
	end

	def destroy
		ingredient = Ingredient.find(params[:id])
		ingredient.destroy
		redirect_to(ingredients_path)
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
		@recipes = Recipe.all
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def create
	recipe = Recipe.create(params[:recipe])
	redirect_to(recipe)
	end

	def new
		@recipe = Recipe.new
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		recipe = Recipe.find(params[:id])
		recipe.update_attributes(params[:recipe])
		redirect_to(recipe)
	end

	def destroy
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<%= f.label :cuisine %>
<%= f.text_field :cuisine %>
<br>
<%= f.label :chef %>
<%= f.text_field :chef %>
<br>
<%= f.label :image %>
<%= f.text_field :image %>
<br>
<%= Recipe.order(:name).each do |recipe %>
	<span><%= recipe.name %></span>
<%= check_box_tag 'book[recipe_ids[]', recipe.id, recipe.in?(@book,recipes.to_a) %>
<% end %>
<%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit book</h1>
<%= render	:partial => 'form' %>

app/views/books/index.html.erb
<ol>
	<% @books.each do |book| %>
<li>
	<ul>
		<li><%= link_to(book.title, book) %></li>
		<li><%= book.cuisine %></li>
		<li><%= book.chef %></li>
		<li><%= image_tag(book.image) %></li>
	</ul>
</li>
<% end %>
</ol>

app/views/books/new.html.erb
<h1>New book</h1>
<%= render	:partial => 'form' %>

app/views/books/show.html.erb
<h2><%= link_to(@book.title, @book) %></h2>
<p><%= @book.cuisine %></p>
<p><%= @book.chef %></p>
<%= image_tag(@book.image) %>

<hr>

<% @book.recipes.each do |recipe| %>
<h3><%= recipe.name %></h3>
	<%= image_tag(recipe.image) %>

<hr>

	<% recipe.ingredients.each do |ingredient| %>
<h4><%= ingredient.name %></h4>
	<%= image_tag(ingredient.image) %>
	<% end %>
<% end %>

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :measurement %>
<%= f.text_field :measurement %>
<br>
<%= f.label :cost %>
<%= f.text_field :cost %>
<br>
<%= f.label :image %>
<%= f.text_field :image %>
<br>
<%= f.submit %>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit ingredient</h1>
<%= render	:partial => 'form' %>

app/views/ingredients/index.html.erb
<ul>
<% @ingredients.each do |ingredient| %>
<li><%= link_to(ingredient.name,ingredient) %></li>
<% end %>
</ul>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>
<%= render	:partial => 'form' %>

app/views/ingredients/show.html.erb
<h3><%= @ingredient.name %></h3>
<%= image_tag(@ingredient.image) %>
<%= link_to 'Delete', @ingredient, :method => :delete %>
<%= link_to 'Edit',edit_ingredient_path(@ingredient) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
<nav>
	
	<ul>
		<li><%= link_to 'Books',books_path %></li>
		<li><%= link_to 'Recipes', recipes_path%></li>
		<li><%= link_to 'Ingredients', ingredients_path%></li>
	</ul>
</nav>

<%= yield %>
</div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :course %>
<%= f.text_field :course %>
<br>
<%= f.label :servingsize %>
<%= f.text_field :servingsize %>
<br>
<%= f.label :instructions %>
<%= f.text_field :instructions %>
<br>
<%= f.label :image %>
<%= f.text_field :image %>
<br>
<%= Ingredient.order(:name).each do |ingredient| %>
<span><%= ingredient.name %></span>
<%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, ingredient.in?(@recipe.ingredients) %>
<% end %>
<%= f.submit %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit recipe</h1>
<%= render	:partial => 'form' %>

app/views/recipes/index.html.erb
<ul>
<% @recipes.each do |recipe| %>
<li><%= link_to(recipe.name,recipe) %></li>
<% end %>
</ul>

app/views/recipes/new.html.erb
<h1>New recipe</h1>
<%= render	:partial => 'form' %>

app/views/recipes/show.html.erb
<h3><%= @recipe.name %></h3>
<%= image_tag(@recipe.image) %>
<%= link_to 'Delete', @recipe, :method => :delete %>
<%= link_to 'Edit',edit_recipe_path(@recipe) %>